#docker-compose file for local development
version: "3.3"
services:
  client:
    build: ./frontend
    environment:
      - VITE_API_URL=app:80
    links:
      - app:80
    ports:
      - "6000:80"
  postgresql_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dis
      - PGPORT=5432
    ports:
      - 6001:5432
    restart: always
    volumes:
      - "database-data:/var/lib/postgresql/data/"
  app:
    build: ./backend/DocIndex.Api
    environment:
      - PG_DB_CONNECTION_STRING=UserID=postgres;Password=postgres;Host=postgresql_db;Port=5432;Database=dis;Pooling=true;MinPoolSize=0;MaxPoolSize=100;ConnectionLifetime=0;
    ports:
      - "6002:8080"
    links:
      - postgresql_db:5432
      - ml-api:80
    depends_on:
      - postgresql_db
    restart: always
    volumes:
      - "app-data:/root/"
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - "q-data:/root/"
  ml-api:
    build: ./ml
    environment:
      - QDRANT_ADDRESS=qdrant:6333
    ports:
      - "6003:80"
    links:
      - qdrant:6333
    depends_on:
      - qdrant
    volumes:
      - "ml-data:/root/"
  goose:
    build: ./backend/migrations
    depends_on:
      - postgresql_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dis
      - DBHOST=postgresql_db
    links:
      - postgresql_db:5432
    volumes:
      - ./backend/migrations:/app/backend/migrations:rw

volumes:
  app-data:
  database-data:
  ml-data:
  q-data: